[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# add more contract to show gas reports
gas_reports = ["Counter.sol"]

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
